### ISSUE TITLE
📍 VOD Development Roadmap V0

### ISSUE THREAD

**Issue by MotzWanted** [VodLM/vod#1]
We summarize our planned features in this issue. This issue will keep being updated.

##### Primary:
- [x] MSMarco
- [x] Natural Question
- [ ] ELI5
- [ ] MMLU
- [ ] Wikipedia
- [ ] WikiHow
##### Secondary:
- [x] Interface for external datasets

##### Primary:
- [x] Implement a REALM model (Encoder + OSS Generative LLM)
##### Secondary:
- [x] Handle LoRA parameterization
- [ ] Handle DeepSpeed
		
##### Primary: 
- [x] Qdrant backend
##### Secondary: 
 - [ ] vector support in elasticsearch

##### Primary:
- [ ] Implement VOD gradients for generative tasks
- [ ] Test VOD gradients on MNIST

##### Primary:
- [x] Make the code plug-an-play / extendable
- [x] Simplify existing workflows
